repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Format code (ruff)
        language: system
        entry: ruff
        args: [format, --diff]
        types: [python]
      - id: ruff-check
        name: Static code analysis (ruff)
        language: system
        entry: ruff
        args: [check]
        types: [python]
      - id: pyright
        name: Type checking (pyright)
        language: system
        entry: pyright
        types: [python]
